added test for HomeController
kurban1998/TestSiteCoreMVC pull request #4
Opened 2022-02-14 08:10 UTC by kurban1998

2022-02-15 18:22 UTC, prbll requested changes

2022-02-15 18:22 UTC, prbll commented on MyDataAccessLayer.UnitTests/IGenericRepositoryTest.cs
> +    public class IGenericRepositoryTest
Обычно классы с тестами называют во множественном числе: GenericRepositoryTests. К тому же это класс, а не интерфейс, почему префикс "I"?

2022-02-15 18:22 UTC, prbll commented on MyWebAppProject.UnitTests/HomeControllerTest.cs
> +    public class HomeControllerTest
Аналогично предыдущему комментарию: название класса во множественном числе

2022-02-15 18:22 UTC, prbll commented on MyWebAppProject.UnitTests/HomeControllerTest.cs
> +        private Mock<IUnitOfWork> _unitOfWorkMock;
Обычно суффикс "Mock" в именах опускают и делают просто _service

2022-02-15 18:22 UTC, prbll commented on MyWebAppProject.UnitTests/HomeControllerTest.cs
> +        private HomeController _controller;
Инстанс тестируемого класса принято называть _target;

2022-02-15 18:22 UTC, prbll commented on MyWebAppProject.UnitTests/HomeControllerTest.cs
> +            _unitOfWorkMock = new Mock<IUnitOfWork>();
Почему не добавил MockBehavior.Strict в параметры при создании мока? Так тесты получаются полноценнее

2022-02-15 18:22 UTC, prbll commented on MyWebAppProject.UnitTests/HomeControllerTest.cs
> +            _unitOfWorkMock = new Mock<IUnitOfWork>();
Касается всех моков

2022-02-15 18:22 UTC, prbll commented on MyWebAppProject.UnitTests/HomeControllerTest.cs
> +        public void TestInitialize()
Давай добавим AAA разделение для всех тестов: arrange, act, assert

2022-02-15 18:22 UTC, prbll commented on MyWebAppProject.UnitTests/HomeControllerTest.cs
> +        public void HomeController_AddToDataBase_SaveSuccess()
Можно немного упростить имя теста: HomeController_AddToDataBase_Success и аналогично следующий тест

2022-02-15 18:22 UTC, prbll commented on MyWebAppProject.UnitTests/HomeControllerTest.cs
> +           _unitOfWorkMock.Verify(x => x.Save(),Times.Once);
Можно ещё сделать VerifyGet, чтобы удостовериться, что Get действительно вызывался. С использованием MockBehavior.Strict особенно стоит этим пользоваться

2022-02-15 18:22 UTC, prbll commented on MyWebAppProject.UnitTests/HomeControllerTest.cs
> +           _controller.AddToDataBase("1", "2", 520);
"1", "2", 520 выглядят как магические числа: https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-best-practices#avoid-magic-strings
Здесь стоит использовать AutoFixture для создания случайных объектов, которые будут передаваться в метод. Аналогично нужно сделать в остальных тестах

2022-02-15 18:22 UTC, prbll commented on MyWebAppProject.UnitTests/HomeControllerTest.cs
> +            //�������� ������ ������ Add � AddToDataBase
Комментарии не отображаются, стоит писать на английском. Чаще всего комментарии в коде пишут на английском, а в идеале комментарии вообще не писать, т.к. хороший код должен быть понятен, сам по себе читаться как комментарий

2022-03-03 20:58 UTC, prbll requested changes

2022-03-03 20:58 UTC, prbll commented on MyDataAccessLayer.UnitTests/GenericRepositoryTests.cs
> +            _target.Add(_pen);
После прогона этого теста в базе данных появляются данные?

2022-03-03 20:58 UTC, prbll commented on MyDataAccessLayer.UnitTests/GenericRepositoryTests.cs
> +        private Fixture _builder = new Fixture();
Обычно переменную типа Fixture называют _fixture. В данном случае ее можно сделать readonly

2022-03-03 20:58 UTC, prbll commented on MyDataAccessLayer.UnitTests/GenericRepositoryTests.cs
> +        private Pen _pen => _builder.Create<Pen>();
Лучше создавать данные в начале каждого теста в секции
 // arrange

2022-03-03 20:58 UTC, prbll commented on MyDataAccessLayer.UnitTests/GenericRepositoryTests.cs
> +            _target.Add(_pen);
Простые юнит-тесты, которые мы сейчас делаем не должны выходить за рамки тестируемого класса. Тест должен только проверять логику внутри тестируемого класса, все !внешние! зависимости должны быть "ненастоящими" моками. В данном случае тест не должен создавать настоящих данных в базу данных. В частности именно из-за этого обычно классы делают зависимыми от интерфейсов, а не от реализаций, т.к. интерфейс можно подменить моком при тестировании.

2022-03-03 20:58 UTC, prbll commented on MyDataAccessLayer.UnitTests/GenericRepositoryTests.cs
> +            _target.Add(_pen);
На самом деле в текущей реализации нормальные юнит тесты не написать на это, но я хотел чтобы ты попробовал и столкнулся с проблемами. Этот файл и UnitOfWorkTests можно удалить

2022-03-03 20:58 UTC, prbll commented on MyWebAppProject.UnitTests/HomeControllerTests.cs
> +        private Fixture _builder = new Fixture();
Аналогичное замечание про Fixture

2022-03-03 20:58 UTC, prbll commented on MyWebAppProject.UnitTests/HomeControllerTests.cs
> +            //Arrange
Обычно оставляют пробел между // и текстом комментария

2022-03-03 20:58 UTC, prbll commented on MyWebAppProject.UnitTests/HomeControllerTests.cs
> +        private double _price => _builder.Create<double>();
Данные стоит создавать в начале каждого теста свои

2022-03-03 20:58 UTC, prbll commented on MyWebAppProject.UnitTests/HomeControllerTests.cs
> +           _target.AddToDataBase(_brand, _color, _price);
Этот тест проходит успешно? Можешь прислать скрин прогона тестов?

2022-03-03 20:58 UTC, prbll commented on MyWebAppProject.UnitTests/HomeControllerTests.cs
> +        public void HomeController_AddToDataBase_AddSuccess()
Чем этот тест отличается от предыдущего?

2022-03-03 20:58 UTC, prbll commented on MyWebAppProject.UnitTests/HomeControllerTests.cs
> +            _unitOfWork.Setup(x => x.PenRepository.GetAll()).Returns(new List<Pen>().AsQueryable);
Возвращаемый List можно создать с помощью Fixture

2022-03-03 20:58 UTC, prbll commented on MyWebAppProject.UnitTests/HomeControllerTests.cs
> +        private double _price => _builder.Create<double>();
Они должны быть локальными переменными в тестах

2022-03-05 08:43 UTC, kurban1998 commented on MyWebAppProject.UnitTests/HomeControllerTests.cs
> +           _target.AddToDataBase(_brand, _color, _price);
![11](https://user-images.githubusercontent.com/90529029/156707847-1d91e388-8783-4d93-bcae-65fcb29e192d.jpg)

2022-03-05 08:43 UTC, kurban1998 commented on MyWebAppProject.UnitTests/HomeControllerTests.cs
> +        public void HomeController_AddToDataBase_AddSuccess()
Проверяет вызывались ли методы Add и Save. Соответственно, если уберу в контроллере `_unitOfWork.Save();` тест не проходит. Вроде как, это работает

2022-03-05 08:43 UTC, kurban1998 commented on MyDataAccessLayer.UnitTests/GenericRepositoryTests.cs
> +            _target.Add(_pen);
В базе нет данных, я не понял как это исправить и что и как  нужно было возвращать. Вылетал ексепшн.

2022-03-05 08:56 UTC, prbll commented on MyWebAppProject.UnitTests/HomeControllerTests.cs
> +        public void HomeController_AddToDataBase_AddSuccess()
Но ведь тесты идентичные

2022-03-05 08:57 UTC, prbll commented on MyWebAppProject.UnitTests/HomeControllerTests.cs
> +           _target.AddToDataBase(_brand, _color, _price);
Окей, тогда стоит добавить 3-ий Verify в тест. Каждому Setup должен соответствовать Verify, проверяющий вызов

2022-03-05 08:58 UTC, prbll commented on MyDataAccessLayer.UnitTests/GenericRepositoryTests.cs
> +            _target.Add(_pen);
То есть эти тесты не проходят и падают?

2022-03-05 09:09 UTC, kurban1998 commented on MyDataAccessLayer.UnitTests/GenericRepositoryTests.cs
> +            _target.Add(_pen);
Нет, не проходят

2022-03-05 09:11 UTC, prbll commented on MyDataAccessLayer.UnitTests/GenericRepositoryTests.cs
> +            _target.Add(_pen);
Стоит у себя на раннем этапе выработать привычку, что код, который не собирается ни в коем случае нельзя пушить в репозиторий, а также нельзя заливать тесты, которые не проходят (тут в некоторых случаях могут быть исключения, но нужно об этом уведомлять коллег).

2022-03-05 09:15 UTC, kurban1998 commented on MyWebAppProject.UnitTests/HomeControllerTests.cs
> +        public void HomeController_AddToDataBase_AddSuccess()
Почему одинаковые, в одном проверяется Save в другом Add или их нужно объединить в один?

2022-03-05 09:20 UTC, prbll commented on MyWebAppProject.UnitTests/HomeControllerTests.cs
> +        public void HomeController_AddToDataBase_AddSuccess()
Да, в один. Разные тесты должны тестировать разную !логику!. То есть разные ветвления в коде, логику в зависимости от возвращаемых значений из каких-либо методов. Здесь же получается, что тест делает одно и то же. И вообще в тесте всегда должны быть Verify на все вызываемые методы в тестируемом классе.

2022-03-22 07:33 UTC, prbll requested changes

2022-03-22 07:33 UTC, prbll commented on MyWebAppProject.UnitTests/HomeControllerTests.cs
> +            string brand = _fixture.Create<string>();
Здесь можно использовать var вместо string. И везде в аналогичных ситуациях

2022-03-23 13:55 UTC, merged