added new project API
kurban1998/TestSiteCoreMVC pull request #7
Opened 2022-06-26 16:55 UTC by kurban1998

2022-07-07 07:54 UTC, prbll requested changes

2022-07-07 07:54 UTC, prbll commented on MyDataAccessLayer/Models/Brand.cs
> +        public Brand()
А почему добавился пустой конструктор?

2022-07-07 07:54 UTC, prbll commented on MyWebAppProject.UnitTests/TodoItemsControllerTests.cs
>  namespace MyWebAppProject.UnitTests
Тесты на Api должны лежать в своем проекте "Имя проекта Api".UnitTests

2022-07-07 07:54 UTC, prbll commented on MyWebAppProject.UnitTests/TodoItemsControllerTests.cs
> -    public class HomeControllerTests
Соответственно тесты на HomeController должны остаться тоже

2022-07-07 07:54 UTC, prbll commented on MyWebAppProject/Controllers/HomeController.cs
> +        private PenBuilder _penBuilder = new PenBuilder();
Нужно использовать readonly IPenBuilder, получать его через конструктор

2022-07-07 07:54 UTC, prbll commented on MyWebAppProject/Controllers/HomeController.cs
> +            var urlForPens = $"https://localhost:44391/api/todoitems";
Url лучше вынести в конфиг файл appsettings.json, создать класс ManagementApiOptions, который будет в себе хранить public Url ManagementApiUrl, создавать этот класс с помощью например https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-6.0#bind-hierarchical-configuration-data-using-the-options-pattern при инициализации приложения
И класть этот объект в контейнер для дальнейшего получения

2022-07-07 07:54 UTC, prbll commented on MyWebAppProject/Controllers/HomeController.cs
> +            List<Pen> pens = new JavaScriptSerializer().Deserialize<List<Pen>>(jsonPens);
Попробуй использовать NewtonsoftJson для десериализации. Не забудь потом удалить старый пакет для десериализации.

2022-07-07 07:54 UTC, prbll commented on MyWebAppProject/Controllers/HomeController.cs
> +            var urlForBrand = $"https://localhost:44391/api/todoitems/brands";
Для получения этого адреса можно будет использовать ManagementApiUrl и через метод combine brands
Аналогично для удаления и других использований url

2022-07-07 07:54 UTC, prbll commented on MyWebAppProject/Controllers/HomeController.cs
> +        private readonly IUnitOfWork _unitOfWork;
IUnitOfWork тут не должно быть теперь

2022-07-07 07:54 UTC, prbll commented on TodoApi/Controllers/TodoItemsController.cs
> +        private PenBuilder _penBuilder = new PenBuilder();
Тоже нужно получать реализацию интерфейса через конструктор

2022-07-07 07:54 UTC, prbll commented on TodoApi/Controllers/TodoItemsController.cs
> +            //post -h Content-Type=application/json -c "{"brand":"AAA","color":"red","price":100}"
Мусорных комментариев в коде быть не должно! Следи за этим!

2022-07-07 07:54 UTC, prbll commented on TodoApi/TodoApi.csproj
> +    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="5.0.2" />
Этот и следующий пакет нужны? Что-то сломается из-за их удаления?

2022-07-07 07:54 UTC, prbll commented on TodoApi/TodoApi.csproj
> +<Project Sdk="Microsoft.NET.Sdk.Web">
Название TodoApi не говорит ни о чем. Это из примера? При адаптации чужого кода нужно не слепо копировать, а именно адаптировать под свои нужны, это касается и имен. Предлагаю название ManagementApi. Не забудь, что соответствующее название должно быть и у проекта с тестами.

2022-07-07 08:26 UTC, kurban1998 commented on MyDataAccessLayer/Models/Brand.cs
> +        public Brand()
Просил для десериализации из JSON в методе Index

2022-07-19 07:13 UTC, prbll requested changes

2022-07-19 07:13 UTC, prbll commented on ManagementApi.UnitTests/HomeControllerTests.cs
> +    public class HomeControllerTests
Почему этот класс остался в этом проекте? Он не тестирует ManagementApi проект!

2022-07-19 07:13 UTC, prbll commented on MyWebAppProject/Controllers/HomeController.cs
> +            var urlForBrand = _apiOptions.ManagementApiUrl.Insert(urlForPens.Length,"/brands");
Попробуй посмотреть на метод Combine для url или же _apiOptions.ManagementApiUrl + "/brands";

2022-07-19 07:13 UTC, prbll commented on MyWebAppProject/Controllers/HomeController.cs
> +            var httpResponseMessage1 =
Именование неудачное. Нужно избегать имен с порядковым номером. Имя должно отражать суть переменной, что в ней хранится. Например pensResponse и brandsResponse

2022-07-19 07:13 UTC, prbll commented on MyWebAppProject/appsettings.json
> +  "UrlAddress": {
Именование настроек не очень удачное:
"ManagementApi": {
    "BaseUrl": "https://localhost:44391/api/ManagementApi"
  },

2022-07-19 17:48 UTC, kurban1998 commented on MyWebAppProject.UnitTests/TodoItemsControllerTests.cs
>  namespace MyWebAppProject.UnitTests
Исправлено.

2022-07-19 17:48 UTC, kurban1998 commented on MyWebAppProject.UnitTests/TodoItemsControllerTests.cs
> -    public class HomeControllerTests
В работе.

2022-07-19 17:48 UTC, kurban1998 commented on MyWebAppProject/Controllers/HomeController.cs
> +        private PenBuilder _penBuilder = new PenBuilder();
Сделано.

2022-07-19 17:48 UTC, kurban1998 commented on MyWebAppProject/Controllers/HomeController.cs
> +            var urlForPens = $"https://localhost:44391/api/todoitems";
Сделано.

2022-07-19 17:48 UTC, kurban1998 commented on MyWebAppProject/Controllers/HomeController.cs
> +            List<Pen> pens = new JavaScriptSerializer().Deserialize<List<Pen>>(jsonPens);
Сделано.

2022-07-19 17:48 UTC, kurban1998 commented on MyWebAppProject/Controllers/HomeController.cs
> +            var urlForBrand = $"https://localhost:44391/api/todoitems/brands";
Сделано.

2022-07-19 17:48 UTC, kurban1998 commented on MyWebAppProject/Controllers/HomeController.cs
> +        private readonly IUnitOfWork _unitOfWork;
Исправлено.

2022-07-19 17:49 UTC, kurban1998 commented on TodoApi/Controllers/TodoItemsController.cs
> +        private PenBuilder _penBuilder = new PenBuilder();
Исправлено.

2022-07-19 17:49 UTC, kurban1998 commented on TodoApi/Controllers/TodoItemsController.cs
> +            //post -h Content-Type=application/json -c "{"brand":"AAA","color":"red","price":100}"
Удалены.

2022-07-19 17:49 UTC, kurban1998 commented on TodoApi/TodoApi.csproj
> +    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="5.0.2" />
Удалены.

2022-07-19 17:49 UTC, kurban1998 commented on TodoApi/TodoApi.csproj
> +<Project Sdk="Microsoft.NET.Sdk.Web">
Исправлено.

2022-07-19 17:49 UTC, kurban1998 commented on ManagementApi.UnitTests/HomeControllerTests.cs
> +    public class HomeControllerTests
Исправлено.

2022-07-19 17:49 UTC, kurban1998 commented on MyWebAppProject/Controllers/HomeController.cs
> +            var urlForBrand = _apiOptions.ManagementApiUrl.Insert(urlForPens.Length,"/brands");
Исправлено.

2022-07-19 17:49 UTC, kurban1998 commented on MyWebAppProject/Controllers/HomeController.cs
> +            var httpResponseMessage1 =
Исправлено.

2022-07-19 17:49 UTC, kurban1998 commented on MyWebAppProject/appsettings.json
> +  "UrlAddress": {
Исправлено.

2022-07-19 18:06 UTC, kurban1998 commented on MyWebAppProject.UnitTests/TodoItemsControllerTests.cs
> -    public class HomeControllerTests
Сделано.

2022-07-19 18:15 UTC, prbll requested changes

2022-07-19 18:15 UTC, prbll commented on ManagementApi.UnitTests/HomeControllerTests.cs
> +    public class HomeControllerTests
Не совсем. Файл остался не в том проекте.
![image](https://user-images.githubusercontent.com/22923229/179820235-e6324d9b-81b4-4c8d-aba7-8e36af7d6ac4.png)

2022-07-19 18:15 UTC, prbll commented on MyWebAppProject/Controllers/HomeController.cs
> +            var pensResponce =
Response - https://dictionary.cambridge.org/dictionary/english/response

2022-07-19 18:15 UTC, prbll commented on MyWebAppProject/Controllers/HomeController.cs
> +            List<Pen> pens = JsonConvert.DeserializeObject<List<Pen>>(jsonPens);
Можно var pens и ниже тожн

2022-07-19 18:17 UTC, prbll commented on MyWebAppProject/Controllers/HomeController.cs
> +                await _httpClient.DeleteAsync(url+penId);
Лучше передавать урл в виде $"{url}/{id}"

2022-07-19 19:25 UTC, kurban1998 commented on MyWebAppProject/Controllers/HomeController.cs
> +            List<Pen> pens = JsonConvert.DeserializeObject<List<Pen>>(jsonPens);
Исправлено.

2022-07-19 19:25 UTC, kurban1998 commented on MyWebAppProject/Controllers/HomeController.cs
> +                await _httpClient.DeleteAsync(url+penId);
Исправлено.

2022-07-19 19:25 UTC, kurban1998 commented on MyWebAppProject/Controllers/HomeController.cs
> +            var pensResponce =
Исправлено.

2022-07-26 06:58 UTC, prbll requested changes

2022-07-26 06:58 UTC, prbll commented on MyWebAppProject/Controllers/HomeController.cs
> +                await _httpClient.GetStringAsync(urlForPens);
В конце асинхронных методов всегда стоит писать .ConfigureAwait(false). Причина этому относительно сложная для понимания на первых этапах, можешь попробовать разобраться: https://johnthiriet.com/configure-await/#:~:text=This%20is%20what%20the%20ConfigureAwait%20method%20enables%20to%20do.&text=Calling%20ConfigureAwait(false)%20after%20the,synchronization%20context%20is%20not%20kept.
Либо в данный момент просто прими на веру, что так нужно делать

2022-07-26 06:58 UTC, prbll commented on MyWebAppProject/Controllers/HomeController.cs
> +                await _httpClient.GetStringAsync(urlForPens);
И ниже тоже

2022-08-02 07:34 UTC, merged